image: atlassian/default-image:3

pipelines:
  default:
    - step:
        script:
          - mkdir -p ~/.ssh
          - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa
          - ssh-keyscan github.com >> ~/.ssh/known_hosts
          - git push --mirror git@github.com:ucguy4u/test.git